version: '3.8'

services:
  # zookeeper:
  #   image: wurstmeister/zookeeper:latest
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - kafka-cassandra-network
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181

  cassandra:
    image: cassandra:latest
    deploy:
      replicas: 2
      placement:
        preferences:
          - spread: node.labels.cassandra == true

        constraints:
          - node.labels.cassandra == true
    ports:
      - "9042:9042"
    networks:
      - event-sourcing
    volumes:
      - cassandra-volume:/var/lib/cassandra
    environment:
      JVM_OPTS: "-Xmx512m -Xms512m"

  # kafka:
  #   image: wurstmeister/kafka:latest
  #   deploy:
  #     replicas: 3
  #     placement:
  #       constraints:
  #         - node.labels.type == kafka
  #   networks:
  #     - kafka-cassandra-network
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: kafka
  #     KAFKA_ADVERTISED_PORT: 9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
  #   volumes:
  #     - kafka-volume:/kafka/data
  #     - kafka-logs:/kafka/logs

networks:
  event-sourcing:
    driver: overlay

volumes:
  cassandra-volume:
  kafka-volume:
  kafka-logs:
